### ISSUE TITLE
Functionality to get similar books

### ISSUE THREAD

**Issue by adeen-s** [chingu-voyage5/Geckos-Team-34#5]
**Please write the User story for this feature**
As a user I want similar books for a book recommended to me so that I can read them in the future

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Return similar books based on a book

**Comment by adeen-s** [comment]
Assigning this to me.

**Comment by adeen-s** [comment]
### List of subtasks for reference:
- Use Tastedive.com API to get similar books
- ~Implement firebase cloud function to get search query and return JSON data~ Find some other workaround since Firebase does not allow outbound requests on the free tier.. This is to protect the API key.
- Parse JSON data to get list of books based on similarity.
- Display the List of books in the desired format of the website.

**Comment by adeen-s** [comment]
#### Interacting with the API:
- Get API key from https://tastedive.com
- The format of the API --> https://tastedive.com/api/similar?q=harry+potter+and+the+order+of+the+phoenix&type=books&k="API KEY HERE"

**Comment by adeen-s** [comment]
### Current Status:
- Built the functionality using vanilla JS

### Todo now:
- Make us of vue for the same functionality

**Comment by Shivam60** [comment]
so i have done it in vanila JS. I return a list of 20 similar books from given book name(i assume book name is correct)
Should I do it in vue now?

**Comment by adeen-s** [comment]
@Shivam60 You should be working on #7 , I got this one.

**Comment by adeen-s** [comment]
@ahegazy I need some help here. I have done the part where I now get the list of similar books. I have appended the list as an object to the similar_books object of ResultsObj. and I can see the output in concole.log().
When I try to display it in book.vue, nothing is shown.

![screenshot from 2018-06-12 15-45-54](https://user-images.githubusercontent.com/13867300/41284843-245d1248-6e58-11e8-94ce-c8087c69deeb.png)

**Comment by ahegazy** [comment]
@adeen-s can I see the code
Can you push it to your fork?

**Comment by adeen-s** [comment]
It's on my fork.

**Comment by ahegazy** [comment]
A PR would be good :D

**Comment by adeen-s** [comment]
I don't want to make an incomplete PR to this repo. I will do it if you want me to, but I do not want to.

**Comment by ahegazy** [comment]
it would be easier to see the difference + we can edit it as we want and it wouldn't affect the main repo ..
