### ISSUE TITLE
Add a state management solution

### ISSUE THREAD

**Issue by danivijay** [chingu-voyage5/Geckos-Team-34#9]
**Describe the bug**
Without state management, handling and mutating data will be difficult.

**Proposed solution**
Add vuex and refactor existing code.

**Comment by danivijay** [comment]
It'll took a day to do it.

**Comment by adeen-s** [comment]
@danivijay while you are working on this separately, could #8 be merged ?

**Comment by danivijay** [comment]
@adeen-s yeah. Actually, I'll start working after the merge.

**Comment by adeen-s** [comment]
Closed by #10
